- name: Check {{ proj }}
  command: git pull
  delegate_to: localhost

- command: date +"%x-%H.%M"
  delegate_to: localhost
  register: timestamp
  tags:
    - build

- name: Compile {{ proj }} image
  docker_image:
    path: ./
    name: "{{ proj }}"
    state: present
    tag: "{{ timestamp.stdout }}"
  delegate_to: localhost
  tags:
    - build

- name: Export image to file
  command: docker save -o {{image}} {{proj}}
  delegate_to: localhost
